
# Site settings
title: 刘梦恒
email:
description: 浙江大学
baseurl: "/liumengheng" # the subpath of your site, e.g. /blog/
url: "http://sherylman.com" # the base hostname & protocol for your site

# User setting
owner: Sherylman
email: sherylmaliu@hmail.com
facebook_username: sherylmanliu
twitter_username: sherylmanliu
github_username: sherylmanliu
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Sherylman

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2
